---
- hosts: api
  vars:
    ansistrano_deploy_to: "www/web-api" # Base path to deploy to.
    ansistrano_version_dir: "releases" # Releases folder name
    ansistrano_current_dir: "current" # Softlink name. You should rarely changed it.
    ansistrano_current_via: "git" # Deployment strategy who code should be deployed to current path. Options are symlink or rsync
    ansistrano_keep_releases: 2 # Releases to keep after a new deployment. See "Pruning old releases".

    ansistrano_git_repo: git-codecommit.us-east-2.amazonaws.com/v1/repos/web-service # Location of the git repository
    ansistrano_git_branch: master # What version of the repository to check out. This can be the full 40-character SHA-1 hash, the literal string HEAD, a branch name, or a tag name
    ansistrano_git_identity_key_path: "/home/pronit/.ssh/csa-git.pem" # If specified this file is copied over and used as the identity key for the git commands, path is relative to the playbook in which it is used
    # Optional variables, omitted by default
    ansistrano_git_refspec: ADDITIONAL_GIT_REFSPEC # Additional refspec to be used by the 'git' module. Uses the same syntax as the 'git fetch' command.
    ansistrano_git_ssh_opts: "-o StrictHostKeyChecking=no" # Additional ssh options to be used in Git
    ansistrano_git_depth: 1 # Additional history truncated to the specified number or revisions

    ansistrano_deplay_after_symlink_tasks_file: "{{ playbook_dir }}/custom-tasks/after-symlink-tasks.yml"
  roles: 
    - ansistrano.deploy